cellsociety_team08: backEnd.GameOfLife Class Reference
backEnd.GameOfLife Class Reference
Public Member Functions
GameOfLife ()
Patch getNext (Patch patch)
int countLiveNeighbors (int liveOnes, List< Patch > theNeighborhood)
Public Member Functions inherited from backEnd.RuleSet
RuleSet ()
void setParams (Map< String, Object > params)
void addGrid (Patch[][] grid)
State getDefaultState ()
Patch initializeRandom (int row, int column)
Patch initializePatch (int row, int column, String s)
String getDescription ()
Patch[][] update ()
List< Patch > getNeighbors (Patch p)
List< Patch > getDirectNeighbors (Patch p)
abstract Patch getNext (Patch curr)
Static Private Attributes
static final String GAME_OF_LIFE = "Game of Life"
Additional Inherited Members
Protected Member Functions inherited from backEnd.RuleSet
void moveCell (Cell toBeMoved)
boolean isOutside (int row, int col)
Protected Attributes inherited from backEnd.RuleSet
String myDescription
State[] myPossibleStates
Map< String, Object > myParams
String gridShape = "Rectangular"
String gridType = "Finite"
Patch[][] myPatches
Static Protected Attributes inherited from backEnd.RuleSet
static final String GRID_SHAPE = "gridShape"
static final String GRID_TYPE = "gridType"
Detailed Description
Definition at line 7 of file GameOfLife.java.
Constructor & Destructor Documentation
backEnd.GameOfLife.GameOfLife ()
Definition at line 13 of file GameOfLife.java.
References backEnd.GameOfLife.GAME_OF_LIFE, backEnd.RuleSet.myDescription, and backEnd.RuleSet.myPossibleStates.
Member Function Documentation
int backEnd.GameOfLife.countLiveNeighbors (int liveOnes, List< Patch > theNeighborhood)
Definition at line 39 of file GameOfLife.java.
References p().
Referenced by backEnd.GameOfLife.getNext().
Patch backEnd.GameOfLife.getNext (Patch patch)
Definition at line 22 of file GameOfLife.java.
References backEnd.Patch.clear(), backEnd.Patch.containsCell(), backEnd.GameOfLife.countLiveNeighbors(), backEnd.Patch.fill(), backEnd.RuleSet.getNeighbors(), and backEnd.RuleSet.myPossibleStates.
Member Data Documentation
final String backEnd.GameOfLife.GAME_OF_LIFE = "Game of Life" static private
Definition at line 9 of file GameOfLife.java.
Referenced by backEnd.GameOfLife.GameOfLife().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/backEnd/GameOfLife.java