cellsociety_team08: frontEnd.CASettings Class Reference
frontEnd.CASettings Class Reference
Public Member Functions
CASettings (String type, Map< String, Object > parametersMap, Integer row, Integer column, String[][] grid)
String getType ()
Map< String, Object > getParameters ()
Integer getRows ()
Integer getColumns ()
String[][] getGrid ()
Protected Attributes
String myGridShape = "Rectangular"
Static Protected Attributes
static Map< String, Object > myParameters
Private Attributes
String myType
Integer myRows
Integer myColumns
String[][] myGrid
Static Private Attributes
static final String GRID_SHAPE = "gridShape"
Detailed Description
CASettings is a data structure that holds all info read from the XML file, including grid size, simulation type, and parameters. CASettings serves to encapsulate this data and pass it from XMLReader to the CALoop, where it is accessed and used to construct the visualization.
Though CASettings is a passive data object, its existence allows XML file-reading to be put into its own specialized class.
Author
Mike Zhu
Definition at line 16 of file CASettings.java.
Constructor & Destructor Documentation
frontEnd.CASettings.CASettings (String type, Map< String, Object > parametersMap, Integer row, Integer column, String grid[][])
Definition at line 27 of file CASettings.java.
Member Function Documentation
Integer frontEnd.CASettings.getColumns ()
Definition at line 52 of file CASettings.java.
References frontEnd.CASettings.myColumns.
Referenced by frontEnd.AnimatorLoop.readXMLAndInitializeGrid(), frontEnd.XMLHandler.write(), and frontEnd.AnimatorLoop.writeToXML().
String [][] frontEnd.CASettings.getGrid ()
Definition at line 56 of file CASettings.java.
References frontEnd.CASettings.myGrid.
Referenced by frontEnd.AnimatorLoop.initGrid(), frontEnd.AnimatorLoop.readXMLAndInitializeGrid(), and frontEnd.XMLHandler.write().
Map<String, Object> frontEnd.CASettings.getParameters ()
Definition at line 44 of file CASettings.java.
References frontEnd.CASettings.myParameters.
Referenced by frontEnd.AnimatorLoop.readXMLAndInitializeGrid(), frontEnd.XMLHandler.write(), and frontEnd.AnimatorLoop.writeToXML().
Integer frontEnd.CASettings.getRows ()
Definition at line 48 of file CASettings.java.
References frontEnd.CASettings.myRows.
Referenced by frontEnd.AnimatorLoop.readXMLAndInitializeGrid(), frontEnd.XMLHandler.write(), and frontEnd.AnimatorLoop.writeToXML().
String frontEnd.CASettings.getType ()
Definition at line 40 of file CASettings.java.
References frontEnd.CASettings.myType.
Referenced by frontEnd.AnimatorLoop.checkBadXMLFileData(), frontEnd.AnimatorLoop.readXMLAndInitializeGrid(), frontEnd.XMLHandler.write(), and frontEnd.AnimatorLoop.writeToXML().
Member Data Documentation
final String frontEnd.CASettings.GRID_SHAPE = "gridShape" static private
Definition at line 18 of file CASettings.java.
Integer frontEnd.CASettings.myColumns private
Definition at line 23 of file CASettings.java.
Referenced by frontEnd.CASettings.getColumns().
String [][] frontEnd.CASettings.myGrid private
Definition at line 24 of file CASettings.java.
Referenced by frontEnd.CASettings.getGrid().
String frontEnd.CASettings.myGridShape = "Rectangular" protected
Definition at line 20 of file CASettings.java.
Referenced by frontEnd.AnimatorLoop.addCellsToGrid().
Map<String, Object> frontEnd.CASettings.myParameters static protected
Definition at line 25 of file CASettings.java.
Referenced by frontEnd.CASettings.getParameters(), frontEnd.Main.makeParamControls(), and frontEnd.Main.readXML().
Integer frontEnd.CASettings.myRows private
Definition at line 22 of file CASettings.java.
Referenced by frontEnd.CASettings.getRows().
String frontEnd.CASettings.myType private
Definition at line 21 of file CASettings.java.
Referenced by frontEnd.CASettings.getType().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/frontEnd/CASettings.java