cellsociety_team08: backEnd.PredatorPrey Class Reference
backEnd.PredatorPrey Class Reference
Public Member Functions
PredatorPrey ()
void setParams (Map< String, Object > params)
Patch[][] update ()
Patch getNext (Patch patch)
Public Member Functions inherited from backEnd.RuleSet
RuleSet ()
void setParams (Map< String, Object > params)
void addGrid (Patch[][] grid)
State getDefaultState ()
Patch initializeRandom (int row, int column)
Patch initializePatch (int row, int column, String s)
String getDescription ()
Patch[][] update ()
List< Patch > getNeighbors (Patch p)
List< Patch > getDirectNeighbors (Patch p)
abstract Patch getNext (Patch curr)
Static Package Attributes
static int sharkStarveTime
static int fishBreedTime
Private Member Functions
Patch[][] makeNextGrid ()
void breedIfNecessary ()
void clearAllFlags ()
boolean checkStarve (Patch patch)
void checkBreed (Patch patch, List< Patch > neighborhood)
List< Patch > findEmpties (List< Patch > neighborhood)
void moveAdj (Patch patch, List< Patch > neighborhood)
void addCell (Patch patch, Cell cell)
void moveOrAddCells ()
boolean checkForFishAndMove (Patch patch, List< Patch > neighborhood)
List< Patch > getPossibleFish (List< Patch > neighborhood)
void eatFish (Patch shark, Patch fish)
void breed (Patch patch, List< Patch > neighborhood)
Private Attributes
Random rand = new Random()
List< Patch > patchesToMove = new ArrayList<Patch>()
Static Private Attributes
static final String SHARK_BREED_TIME = "sharkBreedTime"
static final String SHARK_STARVE_TIME = "sharkStarveTime"
static final String FISH_BREED_TIME = "fishBreedTime"
static int sharkBreedTime
Additional Inherited Members
Protected Member Functions inherited from backEnd.RuleSet
void moveCell (Cell toBeMoved)
boolean isOutside (int row, int col)
Protected Attributes inherited from backEnd.RuleSet
String myDescription
State[] myPossibleStates
Map< String, Object > myParams
String gridShape = "Rectangular"
String gridType = "Finite"
Patch[][] myPatches
Static Protected Attributes inherited from backEnd.RuleSet
static final String GRID_SHAPE = "gridShape"
static final String GRID_TYPE = "gridType"
Detailed Description
Definition at line 10 of file PredatorPrey.java.
Constructor & Destructor Documentation
backEnd.PredatorPrey.PredatorPrey ()
Definition at line 21 of file PredatorPrey.java.
Member Function Documentation
void backEnd.PredatorPrey.addCell (Patch patch, Cell cell) private
Definition at line 173 of file PredatorPrey.java.
References backEnd.Patch.myCell, and p().
Referenced by backEnd.PredatorPrey.breed(), and backEnd.PredatorPrey.moveAdj().
void backEnd.PredatorPrey.breed (Patch patch, List< Patch > neighborhood) private
Definition at line 222 of file PredatorPrey.java.
References backEnd.PredatorPrey.addCell(), backEnd.PredatorPrey.findEmpties(), backEnd.Patch.flag(), backEnd.Patch.getCell(), backEnd.Cell.getState(), backEnd.State.myIndex, and backEnd.RuleSet.myPossibleStates.
Referenced by backEnd.PredatorPrey.checkBreed().
void backEnd.PredatorPrey.breedIfNecessary () private
Definition at line 65 of file PredatorPrey.java.
References backEnd.PredatorPrey.checkBreed(), backEnd.RuleSet.getNeighbors(), and backEnd.RuleSet.myPatches.
Referenced by backEnd.PredatorPrey.update().
void backEnd.PredatorPrey.checkBreed (Patch patch, List< Patch > neighborhood) private
Definition at line 127 of file PredatorPrey.java.
References backEnd.PredatorPrey.breed(), backEnd.PredatorPrey.fishBreedTime, backEnd.Patch.flagged, backEnd.Patch.getCell(), backEnd.Patch.getMyCellState(), backEnd.Cell.getState(), backEnd.Patch.isEmpty, backEnd.Patch.myCell, backEnd.State.myIndex, backEnd.State.myParams, and backEnd.PredatorPrey.sharkBreedTime.
Referenced by backEnd.PredatorPrey.breedIfNecessary().
boolean backEnd.PredatorPrey.checkForFishAndMove (Patch patch, List< Patch > neighborhood) private
Definition at line 185 of file PredatorPrey.java.
References backEnd.PredatorPrey.eatFish(), and backEnd.PredatorPrey.getPossibleFish().
Referenced by backEnd.PredatorPrey.getNext().
boolean backEnd.PredatorPrey.checkStarve (Patch patch) private
Definition at line 112 of file PredatorPrey.java.
References backEnd.Patch.clear(), backEnd.Patch.flag(), backEnd.Patch.getCell(), backEnd.Patch.getMyCellState(), backEnd.Cell.getState(), backEnd.State.myParams, and backEnd.Patch.setMyCellState().
Referenced by backEnd.PredatorPrey.getNext().
void backEnd.PredatorPrey.clearAllFlags () private
Definition at line 74 of file PredatorPrey.java.
References backEnd.Patch.flagged, and backEnd.RuleSet.myPatches.
Referenced by backEnd.PredatorPrey.update().
void backEnd.PredatorPrey.eatFish (Patch shark, Patch fish) private
Definition at line 209 of file PredatorPrey.java.
References backEnd.Patch.clear(), backEnd.Patch.flag(), backEnd.Patch.flagged, backEnd.Patch.getMyCellState(), backEnd.Patch.myCell, backEnd.State.myParams, backEnd.Cell.setState(), and backEnd.PredatorPrey.sharkStarveTime.
Referenced by backEnd.PredatorPrey.checkForFishAndMove().
List<Patch> backEnd.PredatorPrey.findEmpties (List< Patch > neighborhood) private
Definition at line 148 of file PredatorPrey.java.
References p().
Referenced by backEnd.PredatorPrey.breed(), and backEnd.PredatorPrey.moveAdj().
Patch backEnd.PredatorPrey.getNext (Patch patch)
Definition at line 85 of file PredatorPrey.java.
References backEnd.PredatorPrey.checkForFishAndMove(), backEnd.PredatorPrey.checkStarve(), backEnd.Patch.flagged, backEnd.RuleSet.getDirectNeighbors(), backEnd.Patch.getMyCellState(), backEnd.Patch.isEmpty, backEnd.PredatorPrey.moveAdj(), backEnd.Patch.myCell, backEnd.Patch.myCellStateEquals(), and backEnd.RuleSet.myPossibleStates.
Referenced by backEnd.PredatorPrey.makeNextGrid().
List<Patch> backEnd.PredatorPrey.getPossibleFish (List< Patch > neighborhood) private
Definition at line 197 of file PredatorPrey.java.
References p().
Referenced by backEnd.PredatorPrey.checkForFishAndMove().
Patch [][] backEnd.PredatorPrey.makeNextGrid () private
Definition at line 55 of file PredatorPrey.java.
References backEnd.PredatorPrey.getNext(), and backEnd.RuleSet.myPatches.
Referenced by backEnd.PredatorPrey.update().
void backEnd.PredatorPrey.moveAdj (Patch patch, List< Patch > neighborhood) private
Definition at line 159 of file PredatorPrey.java.
References backEnd.PredatorPrey.addCell(), backEnd.Patch.clear(), backEnd.PredatorPrey.findEmpties(), backEnd.Patch.flag(), backEnd.Patch.flagged, and backEnd.Patch.getCell().
Referenced by backEnd.PredatorPrey.getNext().
void backEnd.PredatorPrey.moveOrAddCells () private
Definition at line 179 of file PredatorPrey.java.
References backEnd.RuleSet.myPatches, and p().
Referenced by backEnd.PredatorPrey.update().
void backEnd.PredatorPrey.setParams (Map< String, Object > params)
Definition at line 26 of file PredatorPrey.java.
References backEnd.RuleSet.myPossibleStates.
Patch [][] backEnd.PredatorPrey.update ()
Definition at line 43 of file PredatorPrey.java.
References backEnd.PredatorPrey.breedIfNecessary(), backEnd.Patch.clear(), backEnd.PredatorPrey.clearAllFlags(), backEnd.PredatorPrey.makeNextGrid(), backEnd.PredatorPrey.moveOrAddCells(), and backEnd.RuleSet.myPatches.
Member Data Documentation
final String backEnd.PredatorPrey.FISH_BREED_TIME = "fishBreedTime" static private
Definition at line 14 of file PredatorPrey.java.
int backEnd.PredatorPrey.fishBreedTime static package
Definition at line 15 of file PredatorPrey.java.
Referenced by backEnd.PredatorPrey.checkBreed().
List<Patch> backEnd.PredatorPrey.patchesToMove = new ArrayList<Patch>() private
Definition at line 19 of file PredatorPrey.java.
Random backEnd.PredatorPrey.rand = new Random() private
Definition at line 17 of file PredatorPrey.java.
final String backEnd.PredatorPrey.SHARK_BREED_TIME = "sharkBreedTime" static private
Definition at line 12 of file PredatorPrey.java.
final String backEnd.PredatorPrey.SHARK_STARVE_TIME = "sharkStarveTime" static private
Definition at line 13 of file PredatorPrey.java.
int backEnd.PredatorPrey.sharkBreedTime static private
Definition at line 15 of file PredatorPrey.java.
Referenced by backEnd.PredatorPrey.checkBreed().
int backEnd.PredatorPrey.sharkStarveTime static package
Definition at line 15 of file PredatorPrey.java.
Referenced by backEnd.PredatorPrey.eatFish().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/backEnd/PredatorPrey.java