cellsociety_team08: backEnd.Patch Class Reference
backEnd.Patch Class Reference
Public Member Functions
Patch (int row, int col, boolean empty)
Patch (Patch original)
void changeColor ()
Cell getCell ()
void clear ()
void flag ()
void fill (Cell cell)
boolean containsCell ()
boolean myCellStateEquals (State state)
void setMyCellState (State state)
State getMyCellState ()
Public Attributes
boolean isEmpty
boolean flagged
int myRow
Cell myCell
int numCells
Package Attributes
int myCol
Detailed Description
Definition at line 5 of file Patch.java.
Constructor & Destructor Documentation
backEnd.Patch.Patch (int row, int col, boolean empty)
Definition at line 13 of file Patch.java.
backEnd.Patch.Patch (Patch original)
Cloner constructor. Creates an exact copy of input Patch
Parameters
original = Patch to be cloned
Definition at line 24 of file Patch.java.
References backEnd.Patch.getCell(), backEnd.Patch.myCol, and backEnd.Patch.myRow.
Member Function Documentation
void backEnd.Patch.changeColor ()
Definition at line 31 of file Patch.java.
References backEnd.Cell.getState(), and backEnd.State.myColor.
void backEnd.Patch.clear ()
Definition at line 39 of file Patch.java.
Referenced by backEnd.PredatorPrey.checkStarve(), backEnd.PredatorPrey.eatFish(), backEnd.GameOfLife.getNext(), backEnd.Segregation.getNext(), backEnd.PredatorPrey.moveAdj(), and backEnd.PredatorPrey.update().
boolean backEnd.Patch.containsCell ()
Definition at line 54 of file Patch.java.
Referenced by backEnd.GameOfLife.getNext().
void backEnd.Patch.fill (Cell cell)
Definition at line 49 of file Patch.java.
Referenced by backEnd.SugarScape.clearPatch(), backEnd.GameOfLife.getNext(), backEnd.SpreadingFire.getNext(), backEnd.RuleSet.initializePatch(), backEnd.RuleSet.initializeRandom(), backEnd.SugarScape.moveAgent(), and backEnd.RuleSet.moveCell().
void backEnd.Patch.flag ()
Definition at line 45 of file Patch.java.
Referenced by backEnd.PredatorPrey.breed(), backEnd.PredatorPrey.checkStarve(), backEnd.SugarScape.clearPatch(), backEnd.PredatorPrey.eatFish(), backEnd.PredatorPrey.moveAdj(), and backEnd.SugarScape.moveAgent().
Cell backEnd.Patch.getCell ()
Definition at line 35 of file Patch.java.
References backEnd.Patch.myCell.
Referenced by backEnd.PredatorPrey.breed(), backEnd.PredatorPrey.checkBreed(), backEnd.PredatorPrey.checkStarve(), backEnd.Segregation.getNext(), backEnd.SpreadingFire.isBurning(), backEnd.SugarScape.isSugar(), backEnd.PredatorPrey.moveAdj(), backEnd.Patch.Patch(), and frontEnd.AnimatorLoop.updateGUICells().
State backEnd.Patch.getMyCellState ()
Definition at line 66 of file Patch.java.
References backEnd.Cell.getState().
Referenced by backEnd.PredatorPrey.checkBreed(), backEnd.PredatorPrey.checkStarve(), backEnd.PredatorPrey.eatFish(), and backEnd.PredatorPrey.getNext().
boolean backEnd.Patch.myCellStateEquals (State state)
Definition at line 58 of file Patch.java.
References backEnd.State.equals(), and backEnd.Cell.getState().
Referenced by backEnd.PredatorPrey.getNext().
void backEnd.Patch.setMyCellState (State state)
Definition at line 62 of file Patch.java.
References backEnd.Cell.setState().
Referenced by backEnd.PredatorPrey.checkStarve().
Member Data Documentation
boolean backEnd.Patch.flagged
Definition at line 8 of file Patch.java.
Referenced by backEnd.PredatorPrey.checkBreed(), backEnd.PredatorPrey.clearAllFlags(), backEnd.PredatorPrey.eatFish(), backEnd.SpreadingFire.getNext(), backEnd.PredatorPrey.getNext(), backEnd.SugarScape.getNext(), backEnd.SpreadingFire.isBurning(), backEnd.PredatorPrey.moveAdj(), backEnd.SugarScape.update(), and backEnd.RuleSet.update().
boolean backEnd.Patch.isEmpty
Definition at line 7 of file Patch.java.
Referenced by backEnd.PredatorPrey.checkBreed(), backEnd.SpreadingFire.getNext(), backEnd.PredatorPrey.getNext(), backEnd.SugarScape.getNext(), and backEnd.SpreadingFire.isBurning().
Cell backEnd.Patch.myCell
Definition at line 10 of file Patch.java.
Referenced by backEnd.PredatorPrey.addCell(), backEnd.PredatorPrey.checkBreed(), backEnd.PredatorPrey.eatFish(), backEnd.Patch.getCell(), backEnd.SpreadingFire.getNext(), backEnd.Segregation.getNext(), backEnd.PredatorPrey.getNext(), backEnd.Segregation.getSatisfaction(), backEnd.SugarScape.getSugarLevel(), backEnd.SugarScape.growSugar(), backEnd.SugarScape.setSugarLevel(), and backEnd.SugarScape.testRandomness().
int backEnd.Patch.myCol package
Definition at line 9 of file Patch.java.
Referenced by backEnd.SugarScape.clearPatch(), backEnd.SugarScape.getClosestNeighbor(), backEnd.RuleSet.getDirectNeighbors(), backEnd.RuleSet.getNeighbors(), backEnd.SugarScape.getNeighbors(), backEnd.SpreadingFire.getNext(), backEnd.SugarScape.moveAgent(), and backEnd.Patch.Patch().
int backEnd.Patch.myRow
Definition at line 9 of file Patch.java.
Referenced by backEnd.SugarScape.clearPatch(), backEnd.SugarScape.getClosestNeighbor(), backEnd.RuleSet.getDirectNeighbors(), backEnd.RuleSet.getNeighbors(), backEnd.SugarScape.getNeighbors(), backEnd.SpreadingFire.getNext(), backEnd.SugarScape.moveAgent(), and backEnd.Patch.Patch().
int backEnd.Patch.numCells
Definition at line 11 of file Patch.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/backEnd/Patch.java