cellsociety_team08: frontEnd.Main Class Reference
frontEnd.Main Class Reference
Public Member Functions
void start (Stage mainStage)
void makeControlBox ()
void useControls ()
void playPauseSim ()
void resetSim ()
Static Public Member Functions
static void main (String[] args)
static Popup createPopup (final String message)
static void showPopupMessage (final String message)
Static Public Attributes
static final int HEIGHT = 700
static final int WIDTH = 950
static final int SLIDER_MAX_VALUE = 100
static final int SLIDER_WIDTH = 350
static final int SLIDER_DEFAULT_VALUE = 10
static final int TEXTFIELD_WIDTH = 100
static final int CONTROL_BOX_SPACING = 5
static final int PARAM_CONTROL_BOX_SPACING = 10
static final int PARAM_CONTROL_BOX_WIDTH = 150
Private Member Functions
void makeMenu ()
void makeParamControls ()
void readXML ()
void writeXML ()
Private Attributes
AnimatorLoop myLoop
BorderPane myRoot
HBox myControls
VBox myParamControls
MenuBar myMenuBar
Group myGrid
Button myPauseButton
Slider mySlider
TextField myField
Button myResetButton
Timeline myAnimation
FileChooser fileChooser = new FileChooser()
File XMLFile
Static Private Attributes
static Stage myStage
Detailed Description
Definition at line 34 of file Main.java.
Member Function Documentation
static Popup frontEnd.Main.createPopup (final String message) static
Definition at line 274 of file Main.java.
Referenced by frontEnd.Main.showPopupMessage().
static void frontEnd.Main.main (String[] args) static
Definition at line 247 of file Main.java.
void frontEnd.Main.makeControlBox ()
Definition at line 146 of file Main.java.
Referenced by frontEnd.Main.start().
void frontEnd.Main.makeMenu () private
Creates a drop-down menu at the top of the window
Returns
Definition at line 113 of file Main.java.
References frontEnd.Main.readXML(), and frontEnd.Main.writeXML().
Referenced by frontEnd.Main.start().
void frontEnd.Main.makeParamControls () private
Definition at line 177 of file Main.java.
References frontEnd.CASettings.myParameters, and frontEnd.Main.resetSim().
Referenced by frontEnd.Main.readXML().
void frontEnd.Main.playPauseSim ()
Pause simulation when the Play/Pause key is hit
Definition at line 235 of file Main.java.
Referenced by frontEnd.Main.useControls().
void frontEnd.Main.readXML () private
Definition at line 251 of file Main.java.
References frontEnd.Main.makeParamControls(), frontEnd.CASettings.myParameters, and frontEnd.AnimatorLoop.readXMLAndInitializeGrid().
Referenced by frontEnd.Main.makeMenu(), and frontEnd.Main.resetSim().
void frontEnd.Main.resetSim ()
Definition at line 243 of file Main.java.
References frontEnd.Main.readXML().
Referenced by frontEnd.Main.makeParamControls(), and frontEnd.Main.useControls().
static void frontEnd.Main.showPopupMessage (final String message) static
Definition at line 292 of file Main.java.
References frontEnd.Main.createPopup().
Referenced by frontEnd.AnimatorLoop.checkBadXMLFileData().
void frontEnd.Main.start (Stage mainStage)
Definition at line 69 of file Main.java.
References frontEnd.Main.makeControlBox(), frontEnd.Main.makeMenu(), frontEnd.AnimatorLoop.start(), and frontEnd.Main.useControls().
void frontEnd.Main.useControls ()
Handles controlBox controls (button, slider, textField) Pressing button plays/pauses the simulation Dragging the slider increases/decreases animation speed Entering a number into the TextField currently does nothing
Definition at line 210 of file Main.java.
References frontEnd.Main.playPauseSim(), and frontEnd.Main.resetSim().
Referenced by frontEnd.Main.start().
void frontEnd.Main.writeXML () private
Definition at line 264 of file Main.java.
References frontEnd.AnimatorLoop.writeToXML().
Referenced by frontEnd.Main.makeMenu().
Member Data Documentation
final int frontEnd.Main.CONTROL_BOX_SPACING = 5 static
Definition at line 44 of file Main.java.
FileChooser frontEnd.Main.fileChooser = new FileChooser() private
Definition at line 65 of file Main.java.
final int frontEnd.Main.HEIGHT = 700 static
Definition at line 37 of file Main.java.
Timeline frontEnd.Main.myAnimation private
Definition at line 62 of file Main.java.
HBox frontEnd.Main.myControls private
Definition at line 52 of file Main.java.
TextField frontEnd.Main.myField private
Definition at line 59 of file Main.java.
Group frontEnd.Main.myGrid private
Definition at line 55 of file Main.java.
AnimatorLoop frontEnd.Main.myLoop private
Definition at line 50 of file Main.java.
MenuBar frontEnd.Main.myMenuBar private
Definition at line 54 of file Main.java.
VBox frontEnd.Main.myParamControls private
Definition at line 53 of file Main.java.
Button frontEnd.Main.myPauseButton private
Definition at line 57 of file Main.java.
Button frontEnd.Main.myResetButton private
Definition at line 60 of file Main.java.
BorderPane frontEnd.Main.myRoot private
Definition at line 51 of file Main.java.
Slider frontEnd.Main.mySlider private
Definition at line 58 of file Main.java.
Stage frontEnd.Main.myStage static private
Definition at line 49 of file Main.java.
final int frontEnd.Main.PARAM_CONTROL_BOX_SPACING = 10 static
Definition at line 45 of file Main.java.
final int frontEnd.Main.PARAM_CONTROL_BOX_WIDTH = 150 static
Definition at line 46 of file Main.java.
final int frontEnd.Main.SLIDER_DEFAULT_VALUE = 10 static
Definition at line 42 of file Main.java.
final int frontEnd.Main.SLIDER_MAX_VALUE = 100 static
Definition at line 40 of file Main.java.
final int frontEnd.Main.SLIDER_WIDTH = 350 static
Definition at line 41 of file Main.java.
final int frontEnd.Main.TEXTFIELD_WIDTH = 100 static
Definition at line 43 of file Main.java.
final int frontEnd.Main.WIDTH = 950 static
Definition at line 38 of file Main.java.
File frontEnd.Main.XMLFile private
Definition at line 66 of file Main.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/frontEnd/Main.java