cellsociety_team08: backEnd.RuleSet Class Reference
backEnd.RuleSet Class Reference abstract
Public Member Functions
RuleSet ()
void setParams (Map< String, Object > params)
void addGrid (Patch[][] grid)
State getDefaultState ()
Patch initializeRandom (int row, int column)
Patch initializePatch (int row, int column, String s)
String getDescription ()
Patch[][] update ()
List< Patch > getNeighbors (Patch p)
List< Patch > getDirectNeighbors (Patch p)
abstract Patch getNext (Patch curr)
Protected Member Functions
void moveCell (Cell toBeMoved)
boolean isOutside (int row, int col)
Protected Attributes
String myDescription
State[] myPossibleStates
Map< String, Object > myParams
String gridShape = "Rectangular"
String gridType = "Finite"
Patch[][] myPatches
Static Protected Attributes
static final String GRID_SHAPE = "gridShape"
static final String GRID_TYPE = "gridType"
Private Member Functions
List< Patch > addDirectWrapArounds (List< Patch > list, int row, int col)
List< Patch > addWrapArounds (List< Patch > list, int row, int col)
Private Attributes
Random gridCoord = new Random()
Detailed Description
Definition at line 8 of file RuleSet.java.
Constructor & Destructor Documentation
backEnd.RuleSet.RuleSet ()
Definition at line 23 of file RuleSet.java.
Member Function Documentation
List<Patch> backEnd.RuleSet.addDirectWrapArounds (List< Patch > list, int row, int col) private
Definition at line 197 of file RuleSet.java.
Referenced by backEnd.RuleSet.getDirectNeighbors().
void backEnd.RuleSet.addGrid (Patch grid[][])
Definition at line 36 of file RuleSet.java.
Referenced by frontEnd.AnimatorLoop.readXMLAndInitializeGrid().
List<Patch> backEnd.RuleSet.addWrapArounds (List< Patch > list, int row, int col) private
Definition at line 207 of file RuleSet.java.
Referenced by backEnd.RuleSet.getNeighbors().
State backEnd.RuleSet.getDefaultState ()
Definition at line 40 of file RuleSet.java.
String backEnd.RuleSet.getDescription ()
Definition at line 70 of file RuleSet.java.
References backEnd.RuleSet.myDescription.
List<Patch> backEnd.RuleSet.getDirectNeighbors (Patch p)
Definition at line 151 of file RuleSet.java.
References backEnd.RuleSet.addDirectWrapArounds(), backEnd.RuleSet.getNeighbors(), backEnd.RuleSet.isOutside(), backEnd.Patch.myCol, and backEnd.Patch.myRow.
Referenced by backEnd.SpreadingFire.getNext(), and backEnd.PredatorPrey.getNext().
List<Patch> backEnd.RuleSet.getNeighbors (Patch p)
Definition at line 105 of file RuleSet.java.
References backEnd.RuleSet.addWrapArounds(), backEnd.RuleSet.isOutside(), backEnd.Patch.myCol, and backEnd.Patch.myRow.
Referenced by backEnd.PredatorPrey.breedIfNecessary(), backEnd.RuleSet.getDirectNeighbors(), backEnd.GameOfLife.getNext(), and backEnd.Segregation.getNext().
abstract Patch backEnd.RuleSet.getNext (Patch curr) abstract
Referenced by backEnd.RuleSet.update().
Patch backEnd.RuleSet.initializePatch (int row, int column, String s)
Definition at line 58 of file RuleSet.java.
References backEnd.Patch.fill().
Referenced by frontEnd.AnimatorLoop.initGrid().
Patch backEnd.RuleSet.initializeRandom (int row, int column)
Definition at line 44 of file RuleSet.java.
References backEnd.Patch.fill().
boolean backEnd.RuleSet.isOutside (int row, int col) protected
Definition at line 191 of file RuleSet.java.
Referenced by backEnd.RuleSet.getDirectNeighbors(), backEnd.RuleSet.getNeighbors(), and backEnd.SugarScape.getNeighbors().
void backEnd.RuleSet.moveCell (Cell toBeMoved) protected
Definition at line 90 of file RuleSet.java.
References backEnd.Patch.fill().
Referenced by backEnd.Segregation.getNext().
void backEnd.RuleSet.setParams (Map< String, Object > params)
Definition at line 26 of file RuleSet.java.
Referenced by frontEnd.AnimatorLoop.readXMLAndInitializeGrid().
Patch [][] backEnd.RuleSet.update ()
Definition at line 74 of file RuleSet.java.
References backEnd.Patch.flagged, and backEnd.RuleSet.getNext().
Referenced by frontEnd.AnimatorLoop.updateCells().
Member Data Documentation
final String backEnd.RuleSet.GRID_SHAPE = "gridShape" static protected
Definition at line 10 of file RuleSet.java.
final String backEnd.RuleSet.GRID_TYPE = "gridType" static protected
Definition at line 11 of file RuleSet.java.
Random backEnd.RuleSet.gridCoord = new Random() private
Definition at line 19 of file RuleSet.java.
String backEnd.RuleSet.gridShape = "Rectangular" protected
Definition at line 16 of file RuleSet.java.
Referenced by backEnd.SugarScape.getNeighbors().
String backEnd.RuleSet.gridType = "Finite" protected
Definition at line 17 of file RuleSet.java.
String backEnd.RuleSet.myDescription protected
Definition at line 13 of file RuleSet.java.
Referenced by backEnd.GameOfLife.GameOfLife(), backEnd.RuleSet.getDescription(), backEnd.Segregation.Segregation(), and backEnd.SpreadingFire.SpreadingFire().
Map<String, Object> backEnd.RuleSet.myParams protected
Definition at line 15 of file RuleSet.java.
Referenced by backEnd.SpreadingFire.setParams().
Patch [][] backEnd.RuleSet.myPatches protected
Definition at line 21 of file RuleSet.java.
Referenced by backEnd.PredatorPrey.breedIfNecessary(), backEnd.PredatorPrey.clearAllFlags(), backEnd.SugarScape.getNeighbors(), backEnd.SugarScape.growSugar(), backEnd.PredatorPrey.makeNextGrid(), backEnd.PredatorPrey.moveOrAddCells(), backEnd.SugarScape.randomizeSugar(), backEnd.SugarScape.testRandomness(), backEnd.SugarScape.update(), and backEnd.PredatorPrey.update().
State [] backEnd.RuleSet.myPossibleStates protected
Definition at line 14 of file RuleSet.java.
Referenced by backEnd.PredatorPrey.breed(), backEnd.SugarScape.clearPatch(), backEnd.GameOfLife.GameOfLife(), backEnd.GameOfLife.getNext(), backEnd.SpreadingFire.getNext(), backEnd.PredatorPrey.getNext(), backEnd.SpreadingFire.isBurning(), backEnd.SugarScape.moveAgent(), backEnd.Segregation.Segregation(), backEnd.PredatorPrey.setParams(), backEnd.SugarScape.setParams(), and backEnd.SpreadingFire.SpreadingFire().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/backEnd/RuleSet.java