cellsociety_team08: backEnd.SugarScape Class Reference
backEnd.SugarScape Class Reference
Public Member Functions
SugarScape ()
Patch[][] update ()
void setParams (Map< String, Object > params)
Patch getNext (Patch curr)
Patch getClosestNeighbor (Patch patch, List< Patch > neighbors)
List< Patch > getNeighbors (Patch p)
Public Member Functions inherited from backEnd.RuleSet
RuleSet ()
void setParams (Map< String, Object > params)
void addGrid (Patch[][] grid)
State getDefaultState ()
Patch initializeRandom (int row, int column)
Patch initializePatch (int row, int column, String s)
String getDescription ()
Patch[][] update ()
List< Patch > getNeighbors (Patch p)
List< Patch > getDirectNeighbors (Patch p)
abstract Patch getNext (Patch curr)
Static Package Attributes
static int sugarGrowBackInterval
static int initialSugar
static int sugarMetabolism
static int maxSugar
static int vision
Private Member Functions
void growSugar ()
boolean isSugar (Patch p)
int getSugarLevel (Patch p)
void setSugarLevel (Patch patch, int sugarLevel)
Patch clearPatch (Patch p)
Patch moveAgent (Patch nextPatch)
void subtractMetabolism (Patch nextPatch)
void setupColorMap ()
void addLater (Patch p)
void movePatches (Patch[][] grid)
void randomizeSugar ()
void testRandomness ()
Private Attributes
int ticks = 0
Map< Integer, Color > myColorMap
List< Patch > patchesToMove = new ArrayList<Patch>()
Random rand = new Random()
Static Private Attributes
static final String SUGAR_GROW_BACK_RATE = "sugarGrowBackRate"
static final String SUGAR_GROW_BACK_INTERVAL = "sugarGrowBackInterval"
static final String MAX_SUGAR = "maxSugar"
static final String INITIAL_SUGAR = "initialSugar"
static final String SUGAR_METABOLISM = "sugarMetabolism"
static final String VISION = "vision"
static int sugarGrowBackRate
Additional Inherited Members
Protected Member Functions inherited from backEnd.RuleSet
void moveCell (Cell toBeMoved)
boolean isOutside (int row, int col)
Protected Attributes inherited from backEnd.RuleSet
String myDescription
State[] myPossibleStates
Map< String, Object > myParams
String gridShape = "Rectangular"
String gridType = "Finite"
Patch[][] myPatches
Static Protected Attributes inherited from backEnd.RuleSet
static final String GRID_SHAPE = "gridShape"
static final String GRID_TYPE = "gridType"
Detailed Description
Definition at line 11 of file SugarScape.java.
Constructor & Destructor Documentation
backEnd.SugarScape.SugarScape ()
Definition at line 26 of file SugarScape.java.
Member Function Documentation
void backEnd.SugarScape.addLater (Patch p) private
Definition at line 173 of file SugarScape.java.
Referenced by backEnd.SugarScape.getNext().
Patch backEnd.SugarScape.clearPatch (Patch p) private
Definition at line 142 of file SugarScape.java.
References backEnd.Patch.fill(), backEnd.Patch.flag(), backEnd.Patch.myCol, backEnd.RuleSet.myPossibleStates, backEnd.Patch.myRow, and backEnd.SugarScape.setSugarLevel().
Referenced by backEnd.SugarScape.getNext().
Patch backEnd.SugarScape.getClosestNeighbor (Patch patch, List< Patch > neighbors)
Definition at line 183 of file SugarScape.java.
References backEnd.Patch.myCol, backEnd.Patch.myRow, and p().
Referenced by backEnd.SugarScape.getNext().
List<Patch> backEnd.SugarScape.getNeighbors (Patch p)
Definition at line 214 of file SugarScape.java.
References backEnd.RuleSet.gridShape, backEnd.RuleSet.isOutside(), backEnd.SugarScape.isSugar(), backEnd.Patch.myCol, backEnd.RuleSet.myPatches, and backEnd.Patch.myRow.
Referenced by backEnd.SugarScape.getNext().
Patch backEnd.SugarScape.getNext (Patch curr)
Definition at line 94 of file SugarScape.java.
References backEnd.SugarScape.addLater(), backEnd.SugarScape.clearPatch(), backEnd.Patch.flagged, backEnd.SugarScape.getClosestNeighbor(), backEnd.SugarScape.getNeighbors(), backEnd.SugarScape.getSugarLevel(), backEnd.Patch.isEmpty, backEnd.SugarScape.isSugar(), backEnd.SugarScape.moveAgent(), and backEnd.SugarScape.subtractMetabolism().
Referenced by backEnd.SugarScape.update().
int backEnd.SugarScape.getSugarLevel (Patch p) private
Definition at line 133 of file SugarScape.java.
References backEnd.Cell.getState(), backEnd.Patch.myCell, and backEnd.State.myParams.
Referenced by backEnd.SugarScape.getNext(), backEnd.SugarScape.moveAgent(), and backEnd.SugarScape.subtractMetabolism().
void backEnd.SugarScape.growSugar () private
Definition at line 79 of file SugarScape.java.
References backEnd.Cell.getState(), backEnd.SugarScape.isSugar(), backEnd.SugarScape.maxSugar, backEnd.Patch.myCell, backEnd.State.myColor, backEnd.RuleSet.myPatches, backEnd.SugarScape.setSugarLevel(), and backEnd.SugarScape.sugarGrowBackRate.
Referenced by backEnd.SugarScape.update().
boolean backEnd.SugarScape.isSugar (Patch p) private
Definition at line 129 of file SugarScape.java.
References backEnd.Patch.getCell(), backEnd.Cell.getState(), and backEnd.State.myIndex.
Referenced by backEnd.SugarScape.getNeighbors(), backEnd.SugarScape.getNext(), backEnd.SugarScape.growSugar(), backEnd.SugarScape.randomizeSugar(), and backEnd.SugarScape.testRandomness().
Patch backEnd.SugarScape.moveAgent (Patch nextPatch) private
Definition at line 150 of file SugarScape.java.
References backEnd.Patch.fill(), backEnd.Patch.flag(), backEnd.SugarScape.getSugarLevel(), backEnd.Patch.myCol, backEnd.RuleSet.myPossibleStates, backEnd.Patch.myRow, and backEnd.SugarScape.setSugarLevel().
Referenced by backEnd.SugarScape.getNext().
void backEnd.SugarScape.movePatches (Patch grid[][]) private
Definition at line 177 of file SugarScape.java.
References p().
Referenced by backEnd.SugarScape.update().
void backEnd.SugarScape.randomizeSugar () private
Definition at line 251 of file SugarScape.java.
References backEnd.SugarScape.isSugar(), backEnd.RuleSet.myPatches, and backEnd.SugarScape.setSugarLevel().
void backEnd.SugarScape.setParams (Map< String, Object > params)
Definition at line 59 of file SugarScape.java.
References backEnd.RuleSet.myPossibleStates, and backEnd.SugarScape.setupColorMap().
void backEnd.SugarScape.setSugarLevel (Patch patch, int sugarLevel) private
Definition at line 137 of file SugarScape.java.
References backEnd.Cell.getState(), backEnd.Patch.myCell, backEnd.State.myColor, and backEnd.State.myParams.
Referenced by backEnd.SugarScape.clearPatch(), backEnd.SugarScape.growSugar(), backEnd.SugarScape.moveAgent(), backEnd.SugarScape.randomizeSugar(), and backEnd.SugarScape.subtractMetabolism().
void backEnd.SugarScape.setupColorMap () private
Definition at line 164 of file SugarScape.java.
References backEnd.SugarScape.maxSugar.
Referenced by backEnd.SugarScape.setParams().
void backEnd.SugarScape.subtractMetabolism (Patch nextPatch) private
Definition at line 158 of file SugarScape.java.
References backEnd.SugarScape.getSugarLevel(), backEnd.SugarScape.setSugarLevel(), and backEnd.SugarScape.sugarMetabolism.
Referenced by backEnd.SugarScape.getNext().
void backEnd.SugarScape.testRandomness () private
Definition at line 264 of file SugarScape.java.
References c, backEnd.Cell.getColor(), backEnd.SugarScape.isSugar(), backEnd.Patch.myCell, and backEnd.RuleSet.myPatches.
Patch [][] backEnd.SugarScape.update ()
Definition at line 31 of file SugarScape.java.
References backEnd.Patch.flagged, backEnd.SugarScape.getNext(), backEnd.SugarScape.growSugar(), backEnd.SugarScape.movePatches(), and backEnd.RuleSet.myPatches.
Member Data Documentation
final String backEnd.SugarScape.INITIAL_SUGAR = "initialSugar" static private
Definition at line 16 of file SugarScape.java.
int backEnd.SugarScape.initialSugar static package
Definition at line 19 of file SugarScape.java.
final String backEnd.SugarScape.MAX_SUGAR = "maxSugar" static private
Definition at line 15 of file SugarScape.java.
int backEnd.SugarScape.maxSugar static package
Definition at line 19 of file SugarScape.java.
Referenced by backEnd.SugarScape.growSugar(), and backEnd.SugarScape.setupColorMap().
Map<Integer, Color> backEnd.SugarScape.myColorMap private
Definition at line 21 of file SugarScape.java.
List<Patch> backEnd.SugarScape.patchesToMove = new ArrayList<Patch>() private
Definition at line 22 of file SugarScape.java.
Random backEnd.SugarScape.rand = new Random() private
Definition at line 23 of file SugarScape.java.
final String backEnd.SugarScape.SUGAR_GROW_BACK_INTERVAL = "sugarGrowBackInterval" static private
Definition at line 14 of file SugarScape.java.
final String backEnd.SugarScape.SUGAR_GROW_BACK_RATE = "sugarGrowBackRate" static private
Definition at line 13 of file SugarScape.java.
final String backEnd.SugarScape.SUGAR_METABOLISM = "sugarMetabolism" static private
Definition at line 17 of file SugarScape.java.
int backEnd.SugarScape.sugarGrowBackInterval static package
Definition at line 19 of file SugarScape.java.
int backEnd.SugarScape.sugarGrowBackRate static private
Definition at line 19 of file SugarScape.java.
Referenced by backEnd.SugarScape.growSugar().
int backEnd.SugarScape.sugarMetabolism static package
Definition at line 19 of file SugarScape.java.
Referenced by backEnd.SugarScape.subtractMetabolism().
int backEnd.SugarScape.ticks = 0 private
Definition at line 20 of file SugarScape.java.
final String backEnd.SugarScape.VISION = "vision" static private
Definition at line 18 of file SugarScape.java.
int backEnd.SugarScape.vision static package
Definition at line 19 of file SugarScape.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/backEnd/SugarScape.java