cellsociety_team08: backEnd.Segregation Class Reference
backEnd.Segregation Class Reference
Public Member Functions
Segregation ()
void setParams (Map< String, Object > params)
Patch getNext (Patch patch)
Public Member Functions inherited from backEnd.RuleSet
RuleSet ()
void setParams (Map< String, Object > params)
void addGrid (Patch[][] grid)
State getDefaultState ()
Patch initializeRandom (int row, int column)
Patch initializePatch (int row, int column, String s)
String getDescription ()
Patch[][] update ()
List< Patch > getNeighbors (Patch p)
List< Patch > getDirectNeighbors (Patch p)
abstract Patch getNext (Patch curr)
Static Package Attributes
static float myMinSatB
Private Member Functions
float getSatisfaction (Patch patch, List< Patch > neighborhood)
Static Private Attributes
static final String SEGREGATION = "Segregation"
static final String MIN_SAT_A = "minSatA"
static final String MIN_SAT_B = "minSatB"
static float myMinSatA
Additional Inherited Members
Protected Member Functions inherited from backEnd.RuleSet
void moveCell (Cell toBeMoved)
boolean isOutside (int row, int col)
Protected Attributes inherited from backEnd.RuleSet
String myDescription
State[] myPossibleStates
Map< String, Object > myParams
String gridShape = "Rectangular"
String gridType = "Finite"
Patch[][] myPatches
Static Protected Attributes inherited from backEnd.RuleSet
static final String GRID_SHAPE = "gridShape"
static final String GRID_TYPE = "gridType"
Detailed Description
Definition at line 8 of file Segregation.java.
Constructor & Destructor Documentation
backEnd.Segregation.Segregation ()
Definition at line 16 of file Segregation.java.
References backEnd.RuleSet.myDescription, backEnd.RuleSet.myPossibleStates, and backEnd.Segregation.SEGREGATION.
Member Function Documentation
Patch backEnd.Segregation.getNext (Patch patch)
Definition at line 38 of file Segregation.java.
References backEnd.Patch.clear(), backEnd.Patch.getCell(), backEnd.RuleSet.getNeighbors(), backEnd.Segregation.getSatisfaction(), backEnd.Cell.getState(), backEnd.RuleSet.moveCell(), backEnd.Patch.myCell, backEnd.State.myIndex, and backEnd.Segregation.myMinSatB.
float backEnd.Segregation.getSatisfaction (Patch patch, List< Patch > neighborhood) private
Definition at line 60 of file Segregation.java.
References backEnd.Cell.getState(), and backEnd.Patch.myCell.
Referenced by backEnd.Segregation.getNext().
void backEnd.Segregation.setParams (Map< String, Object > params)
Definition at line 29 of file Segregation.java.
Member Data Documentation
final String backEnd.Segregation.MIN_SAT_A = "minSatA" static private
Definition at line 11 of file Segregation.java.
final String backEnd.Segregation.MIN_SAT_B = "minSatB" static private
Definition at line 12 of file Segregation.java.
float backEnd.Segregation.myMinSatA static private
Definition at line 14 of file Segregation.java.
float backEnd.Segregation.myMinSatB static package
Definition at line 14 of file Segregation.java.
Referenced by backEnd.Segregation.getNext().
final String backEnd.Segregation.SEGREGATION = "Segregation" static private
Definition at line 10 of file Segregation.java.
Referenced by backEnd.Segregation.Segregation().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/backEnd/Segregation.java