cellsociety_team08: backEnd.Cell Class Reference
backEnd.Cell Class Reference
Public Member Functions
Cell (State s)
Color getColor ()
void remove ()
State getState ()
void setState (State s)
Protected Attributes
List< State > myHistory = new Stack<State>()
Detailed Description
Definition at line 8 of file Cell.java.
Constructor & Destructor Documentation
backEnd.Cell.Cell (State s)
Definition at line 12 of file Cell.java.
Member Function Documentation
Color backEnd.Cell.getColor ()
Definition at line 18 of file Cell.java.
References backEnd.Cell.getState(), backEnd.State.myColor, and state.
Referenced by backEnd.SugarScape.testRandomness(), and frontEnd.AnimatorLoop.updateGUICells().
State backEnd.Cell.getState ()
Definition at line 28 of file Cell.java.
Referenced by backEnd.PredatorPrey.breed(), backEnd.Patch.changeColor(), backEnd.PredatorPrey.checkBreed(), backEnd.PredatorPrey.checkStarve(), backEnd.Cell.getColor(), backEnd.Patch.getMyCellState(), backEnd.SpreadingFire.getNext(), backEnd.Segregation.getNext(), backEnd.Segregation.getSatisfaction(), backEnd.SugarScape.getSugarLevel(), backEnd.SugarScape.growSugar(), backEnd.SpreadingFire.isBurning(), backEnd.SugarScape.isSugar(), backEnd.Patch.myCellStateEquals(), and backEnd.SugarScape.setSugarLevel().
void backEnd.Cell.remove ()
Definition at line 24 of file Cell.java.
void backEnd.Cell.setState (State s)
Definition at line 32 of file Cell.java.
Referenced by backEnd.PredatorPrey.eatFish(), and backEnd.Patch.setMyCellState().
Member Data Documentation
List<State> backEnd.Cell.myHistory = new Stack<State>() protected
Definition at line 10 of file Cell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/backEnd/Cell.java