cellsociety_team08: frontEnd.AnimatorLoop Class Reference
frontEnd.AnimatorLoop Class Reference
Public Member Functions
AnimatorLoop (int width, int height)
KeyFrame start ()
Group initGridPane (int gridRows, int gridCols, String[][] gridArray)
Group readXMLAndInitializeGrid (File XMLFile)
void writeToXML ()
Public Attributes
RuleSet myRuleSet
Static Public Attributes
static final int HEIGHT_OFFSET = 112
static final int WIDTH_OFFSET = 190
static final int GRID_BORDER_WIDTH = 1
Private Member Functions
void updateCells ()
void updateGUICells ()
Group addCellsToGrid (String[][] gridArray)
boolean checkBadXMLFileData ()
void initGrid ()
String[][] gridPatchToString ()
void makePossibleShapeFactories ()
void makePossibleRules ()
Private Attributes
CASettings mySettings
double PADDED_WIDTH
double PADDED_HEIGHT
int HEIGHT
int WIDTH
int NUM_ROWS
int NUM_COLS
Group myNodes
ShapeFactory myShapeBuilder
boolean initialized = false
Polygon[][] myGUICells
Patch[][] myPatches
EventHandler< ActionEvent > oneFrame
Static Private Attributes
static final double V_PAD = 0
static final double H_PAD = 0
static Map< String, ShapeFactory > myImplementedShapeFactories
static Map< String, RuleSet > myImplementedRulesets
Detailed Description
Definition at line 26 of file AnimatorLoop.java.
Constructor & Destructor Documentation
frontEnd.AnimatorLoop.AnimatorLoop (int width, int height)
Constructor
Parameters
width = width of stage in pixels
height = height of stage MINUS height of the menu on the top
Definition at line 68 of file AnimatorLoop.java.
References frontEnd.AnimatorLoop.H_PAD, frontEnd.AnimatorLoop.HEIGHT_OFFSET, frontEnd.AnimatorLoop.makePossibleRules(), frontEnd.AnimatorLoop.makePossibleShapeFactories(), frontEnd.AnimatorLoop.V_PAD, and frontEnd.AnimatorLoop.WIDTH_OFFSET.
Member Function Documentation
Group frontEnd.AnimatorLoop.addCellsToGrid (String gridArray[][]) private
Definition at line 137 of file AnimatorLoop.java.
References shapeFactories.ShapeFactory.makeShape(), shapeFactories.ShapeFactory.move(), frontEnd.CASettings.myGridShape, frontEnd.AnimatorLoop.myNodes, frontEnd.AnimatorLoop.NUM_COLS, and frontEnd.AnimatorLoop.NUM_ROWS.
Referenced by frontEnd.AnimatorLoop.initGridPane().
boolean frontEnd.AnimatorLoop.checkBadXMLFileData () private
Definition at line 183 of file AnimatorLoop.java.
References frontEnd.CASettings.getType(), and frontEnd.Main.showPopupMessage().
Referenced by frontEnd.AnimatorLoop.readXMLAndInitializeGrid().
String [][] frontEnd.AnimatorLoop.gridPatchToString () private
Definition at line 214 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.writeToXML().
void frontEnd.AnimatorLoop.initGrid () private
Definition at line 191 of file AnimatorLoop.java.
References frontEnd.CASettings.getGrid(), and backEnd.RuleSet.initializePatch().
Referenced by frontEnd.AnimatorLoop.readXMLAndInitializeGrid().
Group frontEnd.AnimatorLoop.initGridPane (int gridRows, int gridCols, String gridArray[][])
Create the game's scene
Definition at line 126 of file AnimatorLoop.java.
References frontEnd.AnimatorLoop.addCellsToGrid(), and frontEnd.AnimatorLoop.myNodes.
Referenced by frontEnd.AnimatorLoop.readXMLAndInitializeGrid().
void frontEnd.AnimatorLoop.makePossibleRules () private
Definition at line 236 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.AnimatorLoop().
void frontEnd.AnimatorLoop.makePossibleShapeFactories () private
Definition at line 228 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.AnimatorLoop().
Group frontEnd.AnimatorLoop.readXMLAndInitializeGrid (File XMLFile)
Definition at line 161 of file AnimatorLoop.java.
References backEnd.RuleSet.addGrid(), frontEnd.AnimatorLoop.checkBadXMLFileData(), frontEnd.CASettings.getColumns(), frontEnd.CASettings.getGrid(), frontEnd.CASettings.getParameters(), frontEnd.CASettings.getRows(), frontEnd.CASettings.getType(), frontEnd.AnimatorLoop.initGrid(), frontEnd.AnimatorLoop.initGridPane(), frontEnd.AnimatorLoop.myNodes, frontEnd.AnimatorLoop.NUM_COLS, frontEnd.AnimatorLoop.NUM_ROWS, frontEnd.XMLHandler.read(), and backEnd.RuleSet.setParams().
Referenced by frontEnd.Main.readXML().
KeyFrame frontEnd.AnimatorLoop.start ()
Create the game's frame
Definition at line 80 of file AnimatorLoop.java.
References frontEnd.AnimatorLoop.oneFrame.
Referenced by frontEnd.Main.start().
void frontEnd.AnimatorLoop.updateCells () private
Definition at line 94 of file AnimatorLoop.java.
References backEnd.RuleSet.update(), and frontEnd.AnimatorLoop.updateGUICells().
void frontEnd.AnimatorLoop.updateGUICells () private
Change the colors of the Polygon representations of Cells to animate them
Definition at line 104 of file AnimatorLoop.java.
References backEnd.Patch.getCell(), and backEnd.Cell.getColor().
Referenced by frontEnd.AnimatorLoop.updateCells().
void frontEnd.AnimatorLoop.writeToXML ()
Definition at line 201 of file AnimatorLoop.java.
References frontEnd.CASettings.getColumns(), frontEnd.CASettings.getParameters(), frontEnd.CASettings.getRows(), frontEnd.CASettings.getType(), frontEnd.AnimatorLoop.gridPatchToString(), and frontEnd.XMLHandler.write().
Referenced by frontEnd.Main.writeXML().
Member Data Documentation
final int frontEnd.AnimatorLoop.GRID_BORDER_WIDTH = 1 static
Definition at line 31 of file AnimatorLoop.java.
final double frontEnd.AnimatorLoop.H_PAD = 0 static private
Definition at line 36 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.AnimatorLoop().
int frontEnd.AnimatorLoop.HEIGHT private
Definition at line 39 of file AnimatorLoop.java.
final int frontEnd.AnimatorLoop.HEIGHT_OFFSET = 112 static
Definition at line 29 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.AnimatorLoop().
boolean frontEnd.AnimatorLoop.initialized = false private
Definition at line 50 of file AnimatorLoop.java.
Polygon [][] frontEnd.AnimatorLoop.myGUICells private
Definition at line 52 of file AnimatorLoop.java.
Map<String, RuleSet> frontEnd.AnimatorLoop.myImplementedRulesets static private
Definition at line 47 of file AnimatorLoop.java.
Map<String, ShapeFactory> frontEnd.AnimatorLoop.myImplementedShapeFactories static private
Definition at line 46 of file AnimatorLoop.java.
Group frontEnd.AnimatorLoop.myNodes private
Definition at line 44 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.addCellsToGrid(), frontEnd.AnimatorLoop.initGridPane(), and frontEnd.AnimatorLoop.readXMLAndInitializeGrid().
Patch [][] frontEnd.AnimatorLoop.myPatches private
Definition at line 53 of file AnimatorLoop.java.
RuleSet frontEnd.AnimatorLoop.myRuleSet
Definition at line 48 of file AnimatorLoop.java.
CASettings frontEnd.AnimatorLoop.mySettings private
Definition at line 33 of file AnimatorLoop.java.
ShapeFactory frontEnd.AnimatorLoop.myShapeBuilder private
Definition at line 45 of file AnimatorLoop.java.
int frontEnd.AnimatorLoop.NUM_COLS private
Definition at line 42 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.addCellsToGrid(), and frontEnd.AnimatorLoop.readXMLAndInitializeGrid().
int frontEnd.AnimatorLoop.NUM_ROWS private
Definition at line 41 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.addCellsToGrid(), and frontEnd.AnimatorLoop.readXMLAndInitializeGrid().
EventHandler<ActionEvent> frontEnd.AnimatorLoop.oneFrame private
Initial value:
= new EventHandler<ActionEvent>() {
        @Override
        public void handle(ActionEvent evt) {
            updateCells();
        }
    }
Function to do each game frame
Definition at line 87 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.start().
double frontEnd.AnimatorLoop.PADDED_HEIGHT private
Definition at line 38 of file AnimatorLoop.java.
double frontEnd.AnimatorLoop.PADDED_WIDTH private
Definition at line 37 of file AnimatorLoop.java.
final double frontEnd.AnimatorLoop.V_PAD = 0 static private
Definition at line 35 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.AnimatorLoop().
int frontEnd.AnimatorLoop.WIDTH private
Definition at line 40 of file AnimatorLoop.java.
final int frontEnd.AnimatorLoop.WIDTH_OFFSET = 190 static
Definition at line 30 of file AnimatorLoop.java.
Referenced by frontEnd.AnimatorLoop.AnimatorLoop().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/frontEnd/AnimatorLoop.java