cellsociety_team08: backEnd.SpreadingFire Class Reference
backEnd.SpreadingFire Class Reference
Public Member Functions
SpreadingFire ()
void setParams (Map< String, Object > params)
Patch getNext (Patch curr)
Public Member Functions inherited from backEnd.RuleSet
RuleSet ()
void setParams (Map< String, Object > params)
void addGrid (Patch[][] grid)
State getDefaultState ()
Patch initializeRandom (int row, int column)
Patch initializePatch (int row, int column, String s)
String getDescription ()
Patch[][] update ()
List< Patch > getNeighbors (Patch p)
List< Patch > getDirectNeighbors (Patch p)
abstract Patch getNext (Patch curr)
Private Member Functions
boolean isBurning (Patch p)
Private Attributes
Random rand = new Random()
Static Private Attributes
static final String SPREADING_FIRE = "Spreading of Fire"
static final String PROB_CATCH = "probCatch"
static float probCatch
Additional Inherited Members
Protected Member Functions inherited from backEnd.RuleSet
void moveCell (Cell toBeMoved)
boolean isOutside (int row, int col)
Protected Attributes inherited from backEnd.RuleSet
String myDescription
State[] myPossibleStates
Map< String, Object > myParams
String gridShape = "Rectangular"
String gridType = "Finite"
Patch[][] myPatches
Static Protected Attributes inherited from backEnd.RuleSet
static final String GRID_SHAPE = "gridShape"
static final String GRID_TYPE = "gridType"
Detailed Description
Definition at line 9 of file SpreadingFire.java.
Constructor & Destructor Documentation
backEnd.SpreadingFire.SpreadingFire ()
Definition at line 17 of file SpreadingFire.java.
References backEnd.RuleSet.myDescription, backEnd.RuleSet.myPossibleStates, and backEnd.SpreadingFire.SPREADING_FIRE.
Member Function Documentation
Patch backEnd.SpreadingFire.getNext (Patch curr)
Definition at line 37 of file SpreadingFire.java.
References backEnd.State.equals(), backEnd.Patch.fill(), backEnd.Patch.flagged, backEnd.RuleSet.getDirectNeighbors(), backEnd.Cell.getState(), backEnd.SpreadingFire.isBurning(), backEnd.Patch.isEmpty, backEnd.Patch.myCell, backEnd.Patch.myCol, backEnd.RuleSet.myPossibleStates, backEnd.Patch.myRow, and p().
boolean backEnd.SpreadingFire.isBurning (Patch p) private
Definition at line 78 of file SpreadingFire.java.
References backEnd.Patch.flagged, backEnd.Patch.getCell(), backEnd.Cell.getState(), backEnd.Patch.isEmpty, and backEnd.RuleSet.myPossibleStates.
Referenced by backEnd.SpreadingFire.getNext().
void backEnd.SpreadingFire.setParams (Map< String, Object > params)
Definition at line 29 of file SpreadingFire.java.
References backEnd.RuleSet.myParams.
Member Data Documentation
final String backEnd.SpreadingFire.PROB_CATCH = "probCatch" static private
Definition at line 12 of file SpreadingFire.java.
float backEnd.SpreadingFire.probCatch static private
Definition at line 13 of file SpreadingFire.java.
Random backEnd.SpreadingFire.rand = new Random() private
Definition at line 15 of file SpreadingFire.java.
final String backEnd.SpreadingFire.SPREADING_FIRE = "Spreading of Fire" static private
Definition at line 11 of file SpreadingFire.java.
Referenced by backEnd.SpreadingFire.SpreadingFire().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/backEnd/SpreadingFire.java