cellsociety_team08: frontEnd.XMLHandler Class Reference
frontEnd.XMLHandler Class Reference
Public Member Functions
XMLHandler ()
CASettings read (File XMLFile)
void write (CASettings outputSettings)
Private Member Functions
String[][] readGrid (Element gridElem, int rows, int columns)
String[] writeGrid (String[][] grid)
Map< String, Object > readParameters (NodeList params)
Detailed Description
Definition at line 25 of file XMLHandler.java.
Constructor & Destructor Documentation
frontEnd.XMLHandler.XMLHandler ()
Definition at line 27 of file XMLHandler.java.
Member Function Documentation
CASettings frontEnd.XMLHandler.read (File XMLFile)
Reads XML file and returns a CASettings object containing stored info
Parameters
XMLFile
Returns
a CASettings object
Definition at line 36 of file XMLHandler.java.
References frontEnd.XMLHandler.readGrid(), and frontEnd.XMLHandler.readParameters().
Referenced by frontEnd.AnimatorLoop.readXMLAndInitializeGrid().
String [][] frontEnd.XMLHandler.readGrid (Element gridElem, int rows, int columns) private
Definition at line 136 of file XMLHandler.java.
Referenced by frontEnd.XMLHandler.read().
Map<String, Object> frontEnd.XMLHandler.readParameters (NodeList params) private
Definition at line 170 of file XMLHandler.java.
Referenced by frontEnd.XMLHandler.read().
void frontEnd.XMLHandler.write (CASettings outputSettings)
Writes current simulation setup to an XML file.
Parameters
outputSettings = CASettings file representing current type, params, grid from simulation
Definition at line 71 of file XMLHandler.java.
References frontEnd.CASettings.getColumns(), frontEnd.CASettings.getGrid(), frontEnd.CASettings.getParameters(), frontEnd.CASettings.getRows(), frontEnd.CASettings.getType(), and frontEnd.XMLHandler.writeGrid().
Referenced by frontEnd.AnimatorLoop.writeToXML().
String [] frontEnd.XMLHandler.writeGrid (String grid[][]) private
Definition at line 159 of file XMLHandler.java.
Referenced by frontEnd.XMLHandler.write().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team08/repository/src/frontEnd/XMLHandler.java